version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydb
    volumes:
      - .:/usr/src/app
  
  worker:
    build: .
    command: python manage.py rqworker
    depends_on:
      - redis
      - web
    volumes:
      - .:/usr/src/app