# Generated by Django 5.1.7 on 2025-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_cover',
            field=models.FileField(default=2, upload_to='covers'),
            preserve_default=False,
        ),
    ]
