# Generated by Django 5.1.7 on 2025-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_movie_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_cover_phone',
            field=models.FileField(default='', upload_to='phone_covers'),
            preserve_default=False,
        ),
    ]
