# Generated by Django 5.1.7 on 2025-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_movie_author_movie_author_url_movie_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=2015),
            preserve_default=False,
        ),
    ]
