# Generated by Django 5.1.7 on 2025-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_usermovieprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
