# Generated by Django 5.1.7 on 2025-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_watchedmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovieprogress',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='WatchedMovie',
        ),
    ]
